version: '3.7'
x-default: &default
  restart: unless-stopped
  networks:
    - telegraf-net

x-telegraf: &telegraf
  << : *default
  depends_on:
    - influxdb
  image: "telegraf:${TELEGRAF_VERSION?err}-alpine"



x-conviron:
  &conviron
  image: "appf/controller-conviron:0.2.5"
  labels: # these are just for filtering easily
    type: monitor 
    conviron: "true"
  environment:
    GROUP_TAG: "http-monitored"
    USE_HTTP: "true" # if this is set to "false", then you need to specify the telnet port in ADDRESS like "10.132.11.135:23"
  networks:
    - telegraf-net
  
services:
  nginx:
    << : *default
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    ports:
      - '80:80'
      - '443:443'
    cap_add:
      - NET_ADMIN
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Canberra"
      URL: "${DOMAIN?err}"
      SUBDOMAINS: "grafana,influxdb"
      VALIDATION: "http"
      EMAIL: "${LETSENCRYPT_ACCOUNT_EMAIL}"
      # STAGING=true
    volumes:
      - ./nginx/proxy-confs:/config/nginx/proxy-confs
      - /srv:/config/www
      
  influxdb:
    << : *default
    container_name: inflxudb
    image: influxdb:${INFLUXDB_VERSION?err}-alpine
    ports:
      - '8086:8086'
    volumes: 
      - influxdb-storage:/var/lib/influxdb:rw
    environment:  
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "${INFLUXDB_ADMIN_USER?err}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD?err}"
      INFLUXDB_LOGGING_LEVEL: "warn"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "true"
      INFLUXDB_HTTP_LOG_ENABLED: "true"
  grafana:
    << : *default
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION?err}
    depends_on:
      - influxdb
      - smtp
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Anon Org"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_SECURITY_ADMIN_USER: "${GRAFANA_ADMIN_USER?err}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD?err}"
      GF_DEFAULT_INSTANCE_NAME: "grafana.${DOMAIN?err}"
      GF_SERVER_DOMAIN: "grafana.${DOMAIN?err}"
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp:25"
      GF_SMTP_SKIP_VERIFY: "true"
      GF_SMTP_FROM_ADDRESS: "no-reply@grafana.${DOMAIN?err}"
      GF_INSTALL_PLUGINS: "raintank-worldping-app,ryantxu-ajax-panel,fetzerch-sunandmoon-datasource,andig-darksky-datasource"
      TZ: Australia/Canberra
  smtp:
    << : *default
    image: namshi/smtp
    container_name: smtp
    environment:
      - MAILNAME=${DOMAIN?err}

  controller-conviron1:
    <<: *conviron
    container_name: reach-in-1
    environment:
      ADDRESS: "10.199.24.1:23" # this is the ip address of the chamber, without the port
      NAME: "ri1" # change this to the name of your chamber
  controller-conviron2:
    <<: *conviron
    container_name: reach-in-2
    environment:
      ADDRESS: "10.199.24.2:23" # this is the ip address of the chamber, without the port
      NAME: "ri2" # change this to the name of your chamber

  telegraf-conviron:
    # container name is more important here due to the way controller-conviron sends data
    container_name: telegraf
    image: telegraf:${TELEGRAF_VERSION?err}-alpine
    restart: unless-stopped
    networks:
      - telegraf-net
    environment:
      INFLUXDB_URL: "${INFLUXDB_URL}"
      INFLUXDB_DATABASE: "${INFLUXDB_DATABASE}"
      INFLUXDB_USER: "${INFLUXDB_ADMIN_USER}"
      INFLUXDB_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD}"
      TZ: Australia/Canberra
    volumes: 
      - ./telegraf/telegraf-conviron.conf:/etc/telegraf/telegraf.conf:ro
volumes:
  grafana-storage: 
  influxdb-storage:
networks:
  telegraf-net: {}