version: '3.7'
x-default: &default
  restart: unless-stopped
  networks:
    - telegraf-net
x-telegraf: &telegraf
  << : *default
  depends_on:
    - influxdb
  image: "telegraf:${TELEGRAF_VERSION?err}-alpine"

x-conviron:
  &conviron
  image: "appf/controller-conviron:0.2.5"
  labels: # these are just for filtering easily
    type: monitor 
    conviron: "true"
  environment:
    GROUP_TAG: "http-monitored"
    USE_HTTP: "true" # if this is set to "false", then you need to specify the telnet port in ADDRESS like "10.132.11.135:23"
  networks:
    - telegraf-net
  
services:
  #nginx:
  #  << : *default
  #  image: linuxserver/letsencrypt
  #  container_name: nginx
  #  ports:
  #    - '8080:80'
  #    - '8443:443'
  #  cap_add:
  #    - NET_ADMIN
  #  environment:
  #    PUID: "1000"
  #    PGID: "1000"
  #    TZ: "Australia/Canberra"
  #    URL: "${DOMAIN?err}"
  #    SUBDOMAINS: "grafana,influxdb"
  #    VALIDATION: "http"
  #    EMAIL: "${LETSENCRYPT_ACCOUNT_EMAIL}"
  #    # STAGING=true
  #  volumes:
  #    - ./nginx/proxy-confs:/config/nginx/proxy-confs
  #    - /srv:/config/www
      
  influxdb:
    << : *default
    container_name: inflxudb
    image: influxdb:${INFLUXDB_VERSION?err}-alpine
    ports:
      - '8086:8086'
      - '2003:2003'
    volumes: 
      - influxdb-storage:/var/lib/influxdb:rw
    environment:  
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      INFLUXDB_ADMIN_USER: "${INFLUXDB_ADMIN_USER?err}"
      INFLUXDB_ADMIN_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD?err}"
      INFLUXDB_LOGGING_LEVEL: "warn"
      INFLUXDB_DATA_QUERY_LOG_ENABLED: "true"
      INFLUXDB_HTTP_LOG_ENABLED: "true"
      INFLUXDB_GRAPHITE_ENABLED: "true"
  grafana:
    << : *default
    container_name: grafana
    image: grafana/grafana:${GRAFANA_VERSION?err}
    depends_on:
      - influxdb
      - smtp
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    environment:
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Anon Org"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
      GF_SECURITY_ADMIN_USER: "${GRAFANA_ADMIN_USER?err}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD?err}"
      GF_DEFAULT_INSTANCE_NAME: "grafana.${DOMAIN?err}"
      GF_SERVER_DOMAIN: "grafana.${DOMAIN?err}"
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: "smtp:25"
      GF_SMTP_SKIP_VERIFY: "true"
      GF_SMTP_FROM_ADDRESS: "no-reply@grafana.${DOMAIN?err}"
      GF_INSTALL_PLUGINS: "raintank-worldping-app,ryantxu-ajax-panel,fetzerch-sunandmoon-datasource,andig-darksky-datasource"
      TZ: Australia/Canberra
  smtp:
    << : *default
    image: namshi/smtp
    container_name: smtp
    environment:
      - MAILNAME=${DOMAIN?err}

  chronograf:
    << : *default
    container_name: chronograf
    image: chronograf:${CHRONOGRAF_VERSION?err}
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    ports:
      - "8888:8888"
    networks:
      - telegraf-net

  controller-conviron-ri-1:
    <<: *conviron
    container_name: reach-in-1
    environment:
      ADDRESS: "10.199.24.1:23" # this is the ip address of the chamber, without the port
      NAME: "ri1" # change this to the name of your chamber
  controller-conviron-ri-2:
    <<: *conviron
    container_name: reach-in-2
    environment:
      ADDRESS: "10.199.24.2:23" # this is the ip address of the chamber, without the port
      NAME: "ri2" # change this to the name of your chamber
  controller-conviron-ri-3:
    <<: *conviron
    container_name: reach-in-3
    environment:
      ADDRESS: "10.199.24.3:23" # this is the ip address of the chamber, without the port
      NAME: "ri3" # change this to the name of your chamber
  controller-conviron-ri-4:
    <<: *conviron
    container_name: reach-in-4
    environment:
      ADDRESS: "10.199.24.4:23" # this is the ip address of the chamber, without the port
      NAME: "ri4" # change this to the name of your chamber
  controller-conviron-ri-5:
    <<: *conviron
    container_name: reach-in-5
    environment:
      ADDRESS: "10.199.24.5:23" # this is the ip address of the chamber, without the port
      NAME: "ri5" # change this to the name of your chamber
  controller-conviron-ri-6:
    <<: *conviron
    container_name: reach-in-6
    environment:
      ADDRESS: "10.199.24.6:23" # this is the ip address of the chamber, without the port
      NAME: "ri6" # change this to the name of your chamber
  controller-conviron-ri-7:
    <<: *conviron
    container_name: reach-in-7
    environment:
      ADDRESS: "10.199.24.7:23" # this is the ip address of the chamber, without the port
      NAME: "ri7" # change this to the name of your chamber
  controller-conviron-wi-1:
    <<: *conviron
    container_name: walk-in-1
    environment:
      ADDRESS: "10.199.24.8:23" # this is the ip address of the chamber, without the port
      NAME: "wi1" # change this to the name of your chamber
  controller-conviron-wi-2:
    <<: *conviron
    container_name: walk-in-2
    environment:
      ADDRESS: "10.199.24.9:23" # this is the ip address of the chamber, without the port
      NAME: "wi2" # change this to the name of your chamber
  controller-conviron-wi-3:
    <<: *conviron
    container_name: walk-in-3
    environment:
      ADDRESS: "10.199.24.10:23" # this is the ip address of the chamber, without the port
      NAME: "wi3" # change this to the name of your chamber
  controller-conviron-wi-4:
    <<: *conviron
    container_name: walk-in-4
    environment:
      ADDRESS: "10.199.24.11:23" # this is the ip address of the chamber, without the port
      NAME: "wi4" # change this to the name of your chamber
  controller-conviron-wi-5:
    <<: *conviron
    container_name: walk-in-5
    environment:
      ADDRESS: "10.199.24.12:23" # this is the ip address of the chamber, without the port
      NAME: "wi5" # change this to the name of your chamber
  controller-conviron-wi-6:
    <<: *conviron
    container_name: walk-in-6
    environment:
      ADDRESS: "10.199.24.13:23" # this is the ip address of the chamber, without the port
      NAME: "wi6" # change this to the name of your chamber
  controller-conviron-wi-7-ds:
    <<: *conviron
    container_name: walk-in-7
    environment:
      ADDRESS: "10.199.24.14:23" # this is the ip address of the chamber, without the port
      NAME: "wi7" # change this to the name of your chamber
  controller-conviron-wi-8-ds:
    <<: *conviron
    container_name: walk-in-8
    environment:
      ADDRESS: "10.199.24.15:23" # this is the ip address of the chamber, without the port
      NAME: "wi8" # change this to the name of your chamber

  telegraf-conviron:
    # container name is more important here due to the way controller-conviron sends data
    container_name: telegraf
    image: telegraf:${TELEGRAF_VERSION?err}-alpine
    restart: unless-stopped
    networks:
      - telegraf-net
    environment:
      INFLUXDB_URL: "${INFLUXDB_URL}"
      INFLUXDB_DATABASE: "${INFLUXDB_DATABASE}"
      INFLUXDB_USER: "${INFLUXDB_ADMIN_USER}"
      INFLUXDB_PASSWORD: "${INFLUXDB_ADMIN_PASSWORD}"
      DOMAIN: "$DOMAIN"
      TZ: Australia/Canberra
    volumes: 
      - ./telegraf/telegraf-conviron.conf:/etc/telegraf/telegraf.conf:ro
volumes:
  grafana-storage: 
  influxdb-storage:
networks:
  telegraf-net: {}
